-- dirt

return {
  ["barftrail"] = {
    dirtg = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.6 1.0 0.10 1.0	0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -1 r0.5, 0]],
        numparticles       = 2,
        particlelife       = 15,
        particlelifespread = 20,
        particlesize       = [[1 r2]],
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 6,
        pos                = [[r-0.5 r0.5, 1 r2, r-0.5 r0.5]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[flare]],
        useairlos          = false,
		colorchange			= "stuffs",
      },
    },
    dirtw = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
        colormap           = [[1 1 1 0.5	0.5 0.5 1 0.8	0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3 r0.3, 0]],
        numparticles       = 10,
        particlelife       = 15,
        particlelifespread = 20,
        particlesize       = [[7 r4]],
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 6,
        pos                = [[r-0.5 r0.5, 1 r2, r-0.5 r0.5]],
        sizegrowth         = -0.2,
        sizemod            = 1.0,
        texture            = [[new_dirta]],
        useairlos          = false,
      },
    },
  },
  ["barfsplurge"] = {
    dirtg = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.6 1.0 0.10 1.0	0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -1 r0.5, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 20,
        particlesize       = [[1 r2]],
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 6,
        pos                = [[r-0.5 r0.5, 1 r2, r-0.5 r0.5]],
        sizegrowth         = 5,
        sizemod            = 1.0,
        texture            = [[flare]],
        useairlos          = false,
		colorchange			= "stuffs",
      },
    },
	particles = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
        colormap           = [[0.6 1.0 0.10 1.0	0 0 0 0.0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[1, 0, 0]],
        gravity            = [[0, -4, 0]],
        numparticles       = 5,
        particlelife       = [[10]], -- same as groundflash ttl
        particlelifespread = 0,
        particlesize       = 4, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 50,
        pos                = [[r5 r-5, 0, r5 r-5]],
        sizegrowth         = 1, -- same as groundflash circlegrowth
        sizemod            = 0.95,
        texture            = [[randdots]],
      },
    },
  },
  
["barfgas"] = {
	particles = {
	  air                = true,
	  class              = [[CSimpleParticleSystem]],
	  count              = 1,
	  ground             = true,
	  water              = true, 
	  underwater         = true,
	  properties = {
		airdrag            = 0.6,
		alwaysvisible      = true,
		colormap           = [[0.6 1.0 0.05 0.5	0 0 0 0.0]],
		directional        = true,
		emitrot            = 0,
		emitrotspread      = 180,
		emitvector         = [[0, 1, 0]],
		gravity            = [[0, -0.5, 0]],
		numparticles       = 20,
		particlelife       = [[25]], -- same as groundflash ttl
		particlelifespread = 5,
		particlesize       = 8, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
		particlesizespread = 1,
		particlespeed      = 20,
		particlespeedspread = 20,
		pos                = [[r5 r-5, 0, r5 r-5]],
		sizegrowth         = 2, -- same as groundflash circlegrowth
		sizemod            = 1.05,
		texture            = [[flame]],
	  },
	},
  },
}

