return {
  ["love_impact"] = {
	-- put this next to groundflash
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.6,
      circlegrowth       = 12,
      flashalpha         = 0.5,
      flashsize          = 150,
      ground             = true,
      ttl                = 20,
      water              = true, 
	  underwater         = true,
      color = {
        [1]  = 1,
        [2]  = 0.15,
        [3]  = 0.4,
      },
    },
    orangeexplosionspikes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.7 0.8 0.9 0.03   0.9 0.5 0.2 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 8,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 12,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    pinklove = {
      air                = true,
      class              = [[heatcloud]],
      count              = 5,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.5,
        maxheat            = 20,
        pos                = [[r-20 r20, 10, r-20 r20]],
        size               = 1,
        sizegrowth         = 20,
        speed              = [[r10, 10, r10]],
        texture            = [[largelove]],
      },
    },
  },
  ["love_echo"] = {
	-- put this next to groundflash
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.6,
      circlegrowth       = 6,
      flashalpha         = 0.5,
      flashsize          = 150,
      ground             = true,
      ttl                = 20,
      water              = true, 
	  underwater         = true,
      color = {
        [1]  = 1,
        [2]  = 0.15,
        [3]  = 0.4,
      },
    },
    pinklove = {
      air                = true,
      class              = [[heatcloud]],
      count              = 5,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.5,
        maxheat            = 20,
        pos                = [[r-20 r20, 10, r-20 r20]],
        size               = 10,
        sizegrowth         = 10,
        speed              = [[r10, 10, r10]],
        texture            = [[largelove]],
      },
    },
  },

  ["love_hurts"] = {
	explosionwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[1 0 0 0.15	0 0 0 0.0]], 
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 2, 0]],
        numparticles       = 5,
        particlelife       = [[20]], -- same as groundflash ttl
        particlelifespread = 0,
        particlesize       = 2, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 10,
        pos                = [[r20 r-20, -50, r20 r-20]],
        sizegrowth         = 5, -- same as groundflash circlegrowth
        sizemod            = 1.0,
        texture            = [[largelove]],
      },
    },
  },
  
  ["love_heals"] = {
	explosionwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.5 1 1 0.1	0 0 0 0.0]], 
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 2, 0]],
        numparticles       = 5,
        particlelife       = [[20]], -- same as groundflash ttl
        particlelifespread = 0,
        particlesize       = [[15 d1]], -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
        particlesizespread = 1,
        particlespeed      = 100,
        particlespeedspread = 10,
        pos                = [[0,0,0]],
        sizegrowth         = 0, -- same as groundflash circlegrowth
        sizemod            = 1,
        texture            = [[largelove]],
      },
    },
  },
  ["love_golden"] = {
	explosionwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[1 1 0 0.15	0 0 0 0.0]], 
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[1, 0, 0]],
        gravity            = [[0, 2, 0]],
        numparticles       = 5,
        particlelife       = [[20]], -- same as groundflash ttl
        particlelifespread = 0,
        particlesize       = 20, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 15,
        pos                = [[r20 r-20, -50, r20 r-20]],
        sizegrowth         = 5, -- same as groundflash circlegrowth
        sizemod            = 0.95,
        texture            = [[goldlove]],
      },
    },
  },
  ["love_happy"] = {
	explosionwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 4,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
        colormap           = [[1 1 0 0.15	0 0 0 0.0]], 
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[1, 0, 0]],
        gravity            = [[0, -4, 0]],
        numparticles       = 20,
        particlelife       = [[20]], -- same as groundflash ttl
        particlelifespread = 0,
        particlesize       = 40, -- groundflash flashsize 25 = 1, so if flashsize is 200, particlesize here would be 8
        particlesizespread = 1,
        particlespeed      = 50,
        particlespeedspread = 25,
        pos                = [[r20 r-20, -50, r20 r-20]],
        sizegrowth         = 5, -- same as groundflash circlegrowth
        sizemod            = 0.95,
        texture            = [[goldlove]],
      },
    },
  },
}
