return {
	flower4 = {
		blocking = false,
		buildpic = "flower4.png",
		buildcostenergy = 1,
		buildcostmetal = 1,
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 15 -10",
		collisionvolumescales = "28 32 28",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 150,
		name = "Flower4",
		objectname = "flower4.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			shrubs = true,
		},
	},
}
