return {
	flower2 = {
		blocking = false,
		buildpic = "flower2.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "0 0 0",
		collisionvolumetype = "cylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		name = "Flower2",
		objectname = "flower2.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			midposoffset = "0 0 0",
			modelradius = "1",
			shrubs = true,
		},
	},
}
