return {
	flower3 = {
		blocking = false,
		buildpic = "flower3.png",
		buildcostenergy = 1,
		buildcostmetal = 1,
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "10 15 -9",
		collisionvolumescales = "16 32 16",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 150,
		name = "Flower3",
		objectname = "flower3.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			shrubs = true,
		},
	},
}
