return {
	flower2 = {
		blocking = false,
		buildpic = "flower2.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "-1 15 -8",
		collisionvolumescales = "14 32 14",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 150,
		name = "Flower2",
		objectname = "flower2.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			shrubs = true,
		},
	},
}
