return {
	flower6 = {
		blocking = false,
		buildpic = "flower6.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "3 33 -15",
		collisionvolumescales = "27 38 27",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		name = "Flower6",
		objectname = "flower6.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			shrubs = true,
		},
	},
}
