return {
	flower5 = {
		blocking = false,
		buildpic = "flower5.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 30 0",
		collisionvolumescales = "29 52 29",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 150,
		name = "Flower5",
		objectname = "flower5.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			flower = true,
			shrubs = true,
		},
	},
}
