return {
	grass3 = {
		blocking = false,
		buildpic = "grass3.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "-1 15 -8",
		collisionvolumescales = "14 32 14",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		name = "Grass3",
		objectname = "grass3.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			shrubs = true,
		},
	},
}
