return {
	grass2 = {
		blocking = false,
		buildpic = "grass2.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 16 7",
		collisionvolumescales = "20 32 20",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 100,
		name = "Grass2",
		objectname = "grass2.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			shrubs = true,
		},
	},
}
