return {
	grass5 = {
		blocking = false,
		buildcostenergy = 1,
		buildcostmetal = 1,
		buildpic = "grass5.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 16 0",
		collisionvolumescales = "25 32 25",
		collisionvolumetype = "CylY",
		footprintx = 1,
		footprintz = 1,
		mass = 1000000,
		maxdamage = 100,
		name = "Grass5",
		objectname = "grass5.dae",
		pushresistant = true,
		script = "flower.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "o",
		customparams = {
			shrubs = true,
		},
	},
}
