return {
	kingshroom = {
		acceleration = 0.2,
		brakerate = 0.1,
		builder = 0,
		buildpic = "kingshroom.png",
		canattack = 1,
		canguard = 1,
		canmove = 1,
		canpatrol = 1,
		canstop = 1,
		collisionvolumeoffsets = "0 16 0",
		collisionvolumescales = "270 270 270",
		collisionvolumetype = "sphere",
		explodeas = "mushroompop",
		footprintx = 10,
		footprintz = 10,
		holdsteady = true,
		idleautoheal = 0,
		leavetracks = 0,
		maxdamage = 26000,
		maxslope = 15,
		maxvelocity = 50,
		maxwaterdepth = 20,
		movementclass = "Bot2x2",
		name = "King Shroom",
		objectname = "kingshroom.dae",
		radardistance = 0,
		reclaimable = 0,
		releaseheld = true,
		script = "UnitBase.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 400,
		transportcapacity = 10,
		transportsize = 10,
		turninplace = false,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.6,
		turnrate = 3000,
		upright = 0,
		customparams = {
			basepiece = "King",
			centeraim = "KingHead",
			mountanimdefaultto = "headers/weaponmounts/kingshroommouth.lua",
			moveanim = "headers/bipedal_kingmushroom_movement.lua",
			mushroom = true,
			turnaccel = 500,
		},
		weapons = {
		},
	},
}
