return {
	poisonmushroom = {
		acceleration = 0.2,
		brakerate = 0.1,
		builder = 0,
		buildpic = "poisonmushroom.png",
		canattack = 1,
		canguard = 1,
		canmove = 1,
		canpatrol = 1,
		canstop = 1,
		collisionvolumeoffsets = "0 16 0",
		collisionvolumescales = "64 64 64",
		collisionvolumetype = "sphere",
		explodeas = "mushroompop",
		footprintx = 3,
		footprintz = 3,
		holdsteady = true,
		idleautoheal = 0,
		leavetracks = 0,
		maxdamage = 1500,
		maxslope = 15,
		maxvelocity = 62,
		maxwaterdepth = 20,
		movementclass = "Bot2x2",
		name = "Poison Mushroom",
		objectname = "poisonmushroom.dae",
		radardistance = 0,
		reclaimable = 0,
		releaseheld = true,
		script = "UnitBase.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 400,
		transportcapacity = 10,
		transportsize = 10,
		turninplace = false,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.6,
		turnrate = 3000,
		upright = 0,
		customparams = {
			basepiece = "Trunk",
			centeraim = "Trunk",
			mountanimdefaultto = "headers/weaponmounts/shroommouth.lua",
			moveanim = "headers/bipedal_mushroom_movement.lua",
			mushroom = true,
			turnaccel = 500,
		},
		weapondefs = {
			shield = {
				exteriorshield = true,
				name = "Shield",
				shieldalpha = 0.7,
				shieldbadcolor = "0 0 0",
				shieldgoodcolor = "1 0 0.2",
				shieldintercepttype = 3,
				shieldpower = 1000,
				shieldpowerregen = 0,
				shieldpowerregenenergy = 0,
				shieldradius = 200,
				shieldrepulser = false,
				shieldstartingpower = 1000,
				smartshield = true,
				visibleshield = true,
				visibleshieldhitframes = 20,
				visibleshieldrepulse = true,
				weapontype = "Shield",
				damage = {
					default = 10,
				},
			},
		},
		weapons = {
			[1] = {
				def = "Shield",
			},
		},
	},
}
