return {
	smallmushroom = {
		acceleration = 0.8,
		brakerate = 0.1,
		builder = 0,
		buildpic = "smallmushroom.png",
		canattack = 1,
		canguard = 1,
		canmove = 1,
		canpatrol = 1,
		canstop = 1,
		collisionvolumeoffsets = "0 33 7",
		collisionvolumescales = "39 39 39",
		collisionvolumetype = "sphere",
		explodeas = "mushroompop",
		footprintx = 2,
		footprintz = 2,
		holdsteady = true,
		idleautoheal = 0,
		leavetracks = 0,
		maxdamage = 600,
		maxslope = 15,
		maxvelocity = 280,
		maxwaterdepth = 20,
		movementclass = "Bot2x2",
		name = "Small Mushroom",
		objectname = "smallmushroom.dae",
		radardistance = 0,
		reclaimable = 0,
		releaseheld = true,
		script = "UnitBase.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 400,
		transportcapacity = 10,
		transportsize = 10,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.6,
		turnrate = 3000,
		upright = 0,
		customparams = {
			basepiece = "Trunk",
			centeraim = "Trunk",
			mountanimdefaultto = "headers/weaponmounts/shroommouth.lua",
			moveanim = "headers/bipedal_mushroom_movement.lua",
			mushroom = true,
			turnaccel = 500,
		},
		weapons = {
		},
	},
}
