return {
	treelevel2 = {
		blocking = false,
		buildpic = "treelevel2.png",
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		category = "TREE",
		collisionvolumeoffsets = "0 -10 0",
		collisionvolumescales = "100 120 100",
		collisionvolumetype = "cylY",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 0,
		mass = 1000000,
		maxdamage = 500,
		name = "Tree Level 2",
		objectname = "treelevel2.dae",
		pushresistant = true,
		script = "tree.lua",
		shownanoframe = false,
		shownanospray = false,
		sightdistance = 0,
		stealth = true,
		turnrate = 0,
		upright = true,
		yardmap = "oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo",
		customparams = {
			midposoffset = "0 0 0",
			modelradius = "50",
			tree = true,
		},
	},
}
